# This is a basic workflow to help you get started with Actions

name: Update json2

# Controls when the workflow will run
on:
  #status
  #schedule:
  #  - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
        #  fetch-depth: 2
         # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
         
         
#      - name: Commit and push changes
#        run: |
#          echo "${{ github.actor }}"
#          echo "${{ github.actor }}"
#          git config --global user.name "${{ github.actor }}"
#          git config --global user.email "${{ github.actor }}"@gmail.com

#          git add -A
#          git commit -m "commit message"
#          git push
          
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
#          cache: pip
      - name: Run python
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          echo aaa > test.txt
          python dir.py
        env:
          GITHUB_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
          REPOSITORY: '${{ github.repository }}'
          
      - name: tree
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
          ls
