# This is a basic workflow to help you get started with Actions

name: Update json2

# Controls when the workflow will run
on:
  #schedule:
  #  - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        #with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
        #  fetch-depth: 2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run python
        run: |
          python dir.py
          echo "${{ github.actor }}"
          echo "${{ github.actor }}"
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}"@gmail.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          echo aaa > test.txt
          git add test.txt
          git commit -m "json add" -a
          git push origin master
      - name: Run git diff 
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
          ls
