# This is a basic workflow to help you get started with Actions

name: Update json

# Controls when the workflow will run
on: [ 'status' , 'push' ]
#  push:
#    branches:
#      - master
#    paths:
#      - assets/**

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3
#        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
#          fetch-depth: 2
#      - name: Run git diff 
#        run: |
#          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
#          ls -al
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: LS
        run: |
          ls
          echo github.evet.state
          echo '${{ github.evet.description }}'
          echo '${{ github.repository }}'
          echo '${{ secrets.TOKEN }}'
          echo '${{ github.event_path }}'
          echo '${{ github.event.head_commit.message }}'
          echo '${{ github.event.commits[0].message }}'
          echo '${{toJSON(github.event)}}'
